### PR TITLE
Update 1.0.4

### PR DESCRIPTION
**Pull request by MaximeHeckel**
- Fixes request to `/{{photo}}`
- Adds Mongo session storage #5122
- Adds status endpoint #5121
- Adds NewRelic browser #5124
- Fixes Sentry #5123
- UI fixes and improvements

### CODE REVIEW

**Comment by fermayo** [comment]
@Carlaplzgnz you ok with the design changes?

**Comment by ghost** [comment]
Here is a list of fixes: @MaximeHeckel // @fermayo 
- [x] Stack files title is not align properly. it should be align at the center of the main content. (Edit: the problem was  the search bar. It was not  properly aligned with the content)
- [x] Margin from the top nav to the content should be 32px, as in the Tutum app.
- [x] Te content should be 980px wide. Is 950px now
- [x] The "submit to Sktackfiles" button is out of the grid
- [x] Buttons are not consistent with the Style guide.
- [x] When you log in all elements are out of the grid
- [x] Distance between buttons is too large on the stackfile detail must be 8px
- [x] According to the style guide, buttons must never be less than 88px wide. The embed button is 69px wide.
- [x] Ubuntu mono text used for the stackfiles code must be #254356, now is #333
- [x] when you change between My Stacks and Stackfiles the search bar moves
- [x] Search bar is 556px aprox. when the original design is 633px
  <br>
  <br>

I attached some images with examples.

------- IMG-------
<br>

width
<br>

screen shot 2015-09-17 at 10 26 19
<br>

screen shot 2015-09-17 at 10 33 15
<br>
screen shot 2015-09-17 at 10 40 35

**Comment by fermayo** [comment]
@MaximeHeckel can you please review and fix?

**Comment by MaximeHeckel** [comment]
Yep I'm on it.

**Comment by MaximeHeckel** [comment]
@Carlaplzgnz "Buttons are not consistent with the Style guide." ? what does that mean ?

**Comment by MaximeHeckel** [comment]
Buttons require another library.
I'll change that on a specific branch.

**Pull request merged**
